template_path: remote-templates/AccountAlertTopics.yaml
stack_name: AccountAlertTopics
dependencies:
  - bootstrap
parameters:
  InitialSubscriberEmail: "sandbox@sagebase.org"
  EnableSubscriberSMS: "false"
  BillingThreshold: "1000"
  DeployLambda: "true"
  SlackWebhookURL: https://hooks.slack.com/services/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
  SlackChannel: "#infra-notices"
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/AccountAlertTopics.yaml --create-dirs -o remote-templates/AccountAlertTopics.yaml"
