template_path: remote-templates/essentials.yaml
stack_name: essentials
parameters:
  OperatorEmail: tuxingkai1@huawei.com
  VpcPeeringRequesterAwsAccountId: 206727770409
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/essentials.yaml --create-dirs -o remote-templates/essentials.yaml"
